# Generated by Django 4.0.6 on 2022-07-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vortice',
            name='favicon_amarillo',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='favicon_negro',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='logo_amarillo',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='logo_negro',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='favicon'),
        ),
    ]
