# Generated by Django 4.0.6 on 2024-12-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0002_material_producto_prod_prenda_tipo_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material_producto',
            name='material',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
