# Generated by Django 4.0.6 on 2022-07-09 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0002_alter_vortice_favicon_amarillo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coleccion',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='coleccion',
            name='portada',
        ),
    ]
