# Generated by Django 4.0.6 on 2024-12-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0003_alter_material_producto_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='envios_detalle',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='vortice',
            name='envios_img',
            field=models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='preguntas_detalle',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='vortice',
            name='preguntas_img',
            field=models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='terminos_detalle',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='vortice',
            name='terminos_img',
            field=models.ImageField(blank=True, help_text='imagenes 200*200', null=True, upload_to='vortice'),
        ),
    ]
