# Generated by Django 4.0.6 on 2022-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0003_remove_coleccion_icono_remove_coleccion_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='imagen',
            field=models.FileField(blank=True, help_text='100x100', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='imag_prenda_articulo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='100x100', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='muestra_productos',
            name='imagen_1',
            field=models.ImageField(blank=True, help_text='imagenes 504*250', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='muestra_productos',
            name='imagen_2',
            field=models.ImageField(blank=True, help_text='imagenes 250*250', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='muestra_productos',
            name='imagen_3',
            field=models.ImageField(blank=True, help_text='imagenes 250*250', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='muestra_productos',
            name='imagen_4',
            field=models.ImageField(blank=True, help_text='imagenes 504*250', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='muestra_productos',
            name='imagen_5',
            field=models.ImageField(blank=True, help_text='imagenes 504*500', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='favicon_amarillo',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='favicon_negro',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_encabezado',
            field=models.ImageField(blank=True, help_text='imagenes 500*400', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_flot_de_1',
            field=models.ImageField(blank=True, help_text='imagenes 50*50', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_flot_de_2',
            field=models.ImageField(blank=True, help_text='imagenes 50*50', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_flot_iz_1',
            field=models.ImageField(blank=True, help_text='imagenes 50*50', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_flot_iz_2',
            field=models.ImageField(blank=True, help_text='imagenes 50*50', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_fondo',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_pie',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='imagen_suscri',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='logo_amarillo',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='logo_horizontal',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='logo_negro',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='wallpaper',
            field=models.ImageField(blank=True, help_text='imagenes 500*400', null=True, upload_to='vortice/'),
        ),
    ]
