# Generated by Django 4.0.6 on 2022-09-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0004_alter_coleccion_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camiseta_imagen_detalle',
            name='imagen_cuello_o',
            field=models.ImageField(blank=True, help_text='500x500', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='camiseta_imagen_detalle',
            name='imagen_cuello_v_hombre',
            field=models.ImageField(blank=True, help_text='500x500', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='camiseta_imagen_detalle',
            name='imagen_cuello_v_mujer',
            field=models.ImageField(blank=True, help_text='500x500', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galeria_producto_1',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galeria_producto_2',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galeria_producto_3',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galeria_producto_4',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galeria_producto_5',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='galeria_producto_6',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen_2',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen_3',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen_4',
            field=models.ImageField(blank=True, help_text='360x360', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='wallpapers',
            field=models.ImageField(blank=True, help_text='imagenes 500*400', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='youtube',
            field=models.FileField(blank=True, null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='seccion_cliente',
            name='icono',
            field=models.FileField(blank=True, help_text='cuadrada', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='seccion_cliente',
            name='imagen_horizontal',
            field=models.FileField(blank=True, help_text='horizontal', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='seccion_cliente',
            name='imagen_vertical',
            field=models.FileField(blank=True, help_text='vertical', null=True, upload_to='zatuar/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagenes 500*900', null=True, upload_to='vortice/'),
        ),
    ]
