# Generated by Django 4.0.6 on 2025-01-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0004_vortice_envios_detalle_vortice_envios_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='material_produc',
        ),
    ]
