# Generated by Django 4.0.6 on 2022-09-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0005_alter_camiseta_imagen_detalle_imagen_cuello_o_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion_cliente',
            name='icono',
            field=models.FileField(blank=True, help_text='cuadrada', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='seccion_cliente',
            name='imagen_horizontal',
            field=models.FileField(blank=True, help_text='horizontal', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='seccion_cliente',
            name='imagen_vertical',
            field=models.FileField(blank=True, help_text='vertical', null=True, upload_to='vortice/'),
        ),
        migrations.AlterField(
            model_name='vorti_promo',
            name='imagen',
            field=models.ImageField(blank=True, help_text='imagenes 50*50', null=True, upload_to='vortice/'),
        ),
    ]
