# Generated by Django 4.0.6 on 2025-01-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0005_remove_prod_prenda_material_produc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vortice',
            name='envios_detalle',
        ),
        migrations.RemoveField(
            model_name='vortice',
            name='envios_img',
        ),
        migrations.RemoveField(
            model_name='vortice',
            name='preguntas_detalle',
        ),
        migrations.RemoveField(
            model_name='vortice',
            name='preguntas_img',
        ),
        migrations.RemoveField(
            model_name='vortice',
            name='terminos_detalle',
        ),
        migrations.RemoveField(
            model_name='vortice',
            name='terminos_img',
        ),
        migrations.AddField(
            model_name='vortice',
            name='qr_img',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice'),
        ),
    ]
