# Generated by Django 4.0.6 on 2025-01-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0006_remove_vortice_envios_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='qr_prod',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='vortice'),
        ),
    ]
