# Generated by Django 4.0.6 on 2025-01-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0007_prod_prenda_qr_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='link_qr_prod',
            field=models.URLField(blank=True, help_text='Link del producto en payphone', max_length=500, null=True),
        ),
    ]
