# Generated by Django 4.1.13 on 2025-02-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0008_prod_prenda_link_qr_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=999),
            preserve_default=False,
        ),
    ]
