# Generated by Django 4.1.13 on 2025-02-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0009_prod_prenda_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='has_size',
            field=models.BooleanField(default=False),
        ),
    ]
