# Generated by Django 4.1.13 on 2025-02-16 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0010_prod_prenda_has_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prod_prenda',
            old_name='has_size',
            new_name='unica_talla',
        ),
    ]
