# Generated by Django 4.1.13 on 2025-02-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0011_rename_has_size_prod_prenda_unica_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='unica_talla',
        ),
    ]
