# Generated by Django 4.1.13 on 2025-02-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0012_remove_prod_prenda_unica_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='has_sizes',
            field=models.BooleanField(blank=True, default=True, help_text='Si tiene tallas o no'),
        ),
    ]
