# Generated by Django 4.1.13 on 2025-02-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0013_prod_prenda_has_sizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod_prenda',
            options={'verbose_name_plural': '5. Producto'},
        ),
        migrations.AddField(
            model_name='prod_prenda',
            name='tallas_disponibles',
            field=models.CharField(blank=True, help_text='Lista de tallas separadas por comas (ej: S,M,L,XL) o vacío si es talla única.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prod_prenda',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='prod_prenda',
            name='precio_descuent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prod_prenda',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
