# Generated by Django 4.1.13 on 2025-02-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0014_alter_prod_prenda_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prod_prenda',
            options={'verbose_name_plural': '5. Producto '},
        ),
        migrations.RemoveField(
            model_name='prod_prenda',
            name='tallas_disponibles',
        ),
        migrations.AlterField(
            model_name='prod_prenda',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=999),
        ),
        migrations.AlterField(
            model_name='prod_prenda',
            name='precio_descuent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=999, null=True),
        ),
        migrations.AlterField(
            model_name='prod_prenda',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=999),
        ),
    ]
