# Generated by Django 4.1.13 on 2025-02-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0015_alter_prod_prenda_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='has_sizes',
        ),
    ]
