# Generated by Django 4.1.13 on 2025-02-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0016_remove_prod_prenda_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='has_sizes',
            field=models.BooleanField(default=True),
        ),
    ]
