# Generated by Django 4.1.13 on 2025-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0017_prod_prenda_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='prod_prenda',
            name='talla_unica',
            field=models.BooleanField(default=False),
        ),
    ]
