# Generated by Django 4.1.13 on 2025-02-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0018_remove_prod_prenda_has_sizes_prod_prenda_talla_unica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='talla_unica',
        ),
        migrations.AddField(
            model_name='prod_prenda',
            name='has_sizes',
            field=models.BooleanField(default=True),
        ),
    ]
