# Generated by Django 4.1.13 on 2025-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0019_remove_prod_prenda_talla_unica_prod_prenda_has_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='size_type',
            field=models.CharField(choices=[('ropa', 'Ropa (S, M, L, XL, XXL)'), ('zapatos', 'Zapatos (36-45)'), ('unica', 'Talla Única')], default='ropa', max_length=10),
        ),
    ]
