# Generated by Django 4.1.13 on 2025-02-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0021_remove_prod_prenda_has_sizes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='tipo_talla',
            field=models.CharField(choices=[('unica', 'Talla Única'), ('ropa', 'Tallas de Ropa'), ('zapatos', 'Tallas de Zapatos'), ('otros', 'Otras Tallas')], default='unica', max_length=10),
        ),
    ]
