# Generated by Django 4.1.13 on 2025-02-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0022_prod_prenda_tipo_talla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='tipo_talla',
        ),
        migrations.AddField(
            model_name='prod_prenda',
            name='has_sizes',
            field=models.BooleanField(default=True),
        ),
    ]
