# Generated by Django 4.1.13 on 2025-02-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0023_remove_prod_prenda_tipo_talla_prod_prenda_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='has_sizes',
        ),
    ]
