# Generated by Django 4.1.13 on 2025-02-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0025_prod_prenda_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod_prenda',
            name='activa_descuento',
        ),
        migrations.RemoveField(
            model_name='prod_prenda',
            name='link_qr_prod',
        ),
        migrations.RemoveField(
            model_name='prod_prenda',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='prod_prenda',
            name='precio_descuent',
        ),
        migrations.RemoveField(
            model_name='prod_prenda',
            name='qr_prod',
        ),
    ]
