# Generated by Django 4.1.13 on 2025-02-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0026_remove_prod_prenda_activa_descuento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='meta_about',
            field=models.ImageField(blank=True, help_text='imagenes 1200x630 px', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='meta_gifcard',
            field=models.ImageField(blank=True, help_text='imagenes 1200x630 px', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='meta_hombre',
            field=models.ImageField(blank=True, help_text='imagenes 1200x630 px', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='meta_inicio',
            field=models.ImageField(blank=True, help_text='imagenes 1200x630 px', null=True, upload_to='vortice'),
        ),
        migrations.AddField(
            model_name='vortice',
            name='meta_mujer',
            field=models.ImageField(blank=True, help_text='imagenes 1200x630 px', null=True, upload_to='vortice'),
        ),
    ]
