# Generated by Django 4.1.13 on 2025-02-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0027_vortice_meta_about_vortice_meta_gifcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='meta_moda',
            field=models.ImageField(blank=True, help_text='imagenes 1200x630 px', null=True, upload_to='vortice'),
        ),
    ]
