# Generated by Django 4.1.13 on 2025-02-20 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0028_vortice_meta_moda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produc_color',
            name='color',
        ),
        migrations.RemoveField(
            model_name='produc_color',
            name='produc_prenda',
        ),
        migrations.RemoveField(
            model_name='talla_camiseta',
            name='produc',
        ),
        migrations.RemoveField(
            model_name='talla_camiseta',
            name='talla_camisetas',
        ),
        migrations.RemoveField(
            model_name='talla_producto',
            name='produc',
        ),
        migrations.RemoveField(
            model_name='talla_producto',
            name='talla_producto',
        ),
        migrations.RemoveField(
            model_name='talla_zapato',
            name='produc',
        ),
        migrations.RemoveField(
            model_name='talla_zapato',
            name='talla_zapatos',
        ),
        migrations.DeleteModel(
            name='Colores',
        ),
        migrations.DeleteModel(
            name='Nu_Talla_Cami',
        ),
        migrations.DeleteModel(
            name='Nu_Talla_Produ',
        ),
        migrations.DeleteModel(
            name='Nu_Talla_Zapa',
        ),
        migrations.DeleteModel(
            name='Produc_Color',
        ),
        migrations.DeleteModel(
            name='Talla_Camiseta',
        ),
        migrations.DeleteModel(
            name='Talla_Producto',
        ),
        migrations.DeleteModel(
            name='Talla_Zapato',
        ),
    ]
