# Generated by Django 4.1.13 on 2025-02-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0029_remove_produc_color_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SliderCard',
        ),
    ]
