# Generated by Django 4.1.13 on 2025-02-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0030_delete_slidercard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='about_04_imagen_2',
            field=models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice'),
        ),
        migrations.AlterField(
            model_name='coleccion',
            name='imag_colec_02',
            field=models.FileField(blank=True, help_text='slider inicio horizontal', null=True, upload_to='vortice'),
        ),
    ]
