# Generated by Django 4.1.13 on 2025-02-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0031_vortice_about_04_imagen_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vortice',
            name='img_termi_condi',
            field=models.ImageField(blank=True, help_text='imagenes 2000 × 1262 px', null=True, upload_to='vortice'),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='about_03_imagen',
            field=models.ImageField(blank=True, help_text='imagenes logo', null=True, upload_to='vortice'),
        ),
    ]
