# Generated by Django 4.1.13 on 2025-03-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0032_vortice_img_termi_condi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_prenda',
            name='descripcion_produc',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
