# Generated by Django 4.1.13 on 2025-03-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0033_alter_prod_prenda_descripcion_produc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imag_prenda_articulo',
        ),
    ]
