# Generated by Django 4.2.20 on 2025-03-07 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0034_delete_imag_prenda_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_prenda',
            name='tipo_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vortice.material_producto'),
        ),
    ]
