# Generated by Django 4.2.20 on 2025-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0036_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
