# Generated by Django 4.2.20 on 2025-03-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0037_banco_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
