# Generated by Django 4.2.20 on 2025-06-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0038_alter_banco_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='seccion_cliente',
            name='mostrar',
            field=models.BooleanField(default=False),
        ),
    ]
