# Generated by Django 4.2.20 on 2025-06-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0039_seccion_cliente_mostrar'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
