# Generated by Django 4.2.20 on 2025-07-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0040_prod_prenda_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='estado',
            field=models.CharField(choices=[('disp', 'Disponible'), ('agot', 'Agotado'), ('reserv', 'Reservado')], default='disp', help_text='Selecciona si está disponible, agotado o reservado.', max_length=6, verbose_name='Estado del producto'),
        ),
    ]
