# Generated by Django 4.2.20 on 2025-07-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0042_alter_seccion_cliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_articulo',
            name='activo_menu_colec',
            field=models.BooleanField(default=False),
        ),
    ]
