# Generated by Django 4.2.20 on 2025-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0043_tipo_articulo_activo_menu_colec'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='imagen_produc_03',
            field=models.ImageField(blank=True, help_text='horizontal', null=True, upload_to='vortice'),
        ),
    ]
