# Generated by Django 4.2.20 on 2025-07-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0045_coleccion_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_prenda',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
