# Generated by Django 4.2.20 on 2026-05-31 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0046_prod_prenda_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_prenda',
            name='descripcion_produc',
            field=models.TextField(blank=True, help_text='Usar solo si deseas escribir una descripción personalizada.', max_length=400, null=True),
        ),
        migrations.CreateModel(
            name='DetallePrendaColeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_detalle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del detalle')),
                ('detalle', models.TextField(blank=True, max_length=800, null=True, verbose_name='Detalle de la prenda')),
                ('activo', models.BooleanField(default=True)),
                ('coleccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.coleccion')),
                ('tipo_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.tipo_articulo')),
            ],
            options={
                'verbose_name_plural': '4. Detalles de prendas por colección',
            },
        ),
        migrations.AddField(
            model_name='prod_prenda',
            name='detalle_prenda',
            field=models.ForeignKey(blank=True, help_text='Selecciona el detalle según la colección y tipo de prenda.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vortice.detalleprendacoleccion', verbose_name='Detalle de prenda'),
        ),
    ]
