# Generated by Django 4.2.20 on 2026-05-31 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0047_alter_prod_prenda_descripcion_produc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleprendacoleccion',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='detalleprendacoleccion',
            name='nombre_detalle',
        ),
        migrations.AlterField(
            model_name='detalleprendacoleccion',
            name='tipo_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Vortice.tipo_articulo', verbose_name='Tipo de artículo'),
        ),
    ]
