# Generated by Django 4.2.20 on 2026-05-31 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0048_remove_detalleprendacoleccion_coleccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipo_articulo',
            options={'ordering': ['nombre_articulo'], 'verbose_name_plural': '4. Tipo de Articulo '},
        ),
    ]
