# Generated by Django 4.2.20 on 2026-05-31 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0049_alter_tipo_articulo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleprendacoleccion',
            options={'ordering': ['tipo_articulo__coleccion__cliente__cliente', 'tipo_articulo__coleccion__tema_colec', 'tipo_articulo__nombre_articulo'], 'verbose_name_plural': '4. Detalles de prendas por colección'},
        ),
    ]
