# Generated by Django 4.2.30 on 2026-09-19 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vortice', '0050_alter_detalleprendacoleccion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vortice',
            name='about_subtitulo_02',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='about_subtitulo_03',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='vortice',
            name='about_subtitulo_04',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
