# Generated by Django 4.0.6 on 2024-11-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Niska', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='logo_horizontal',
            new_name='logo_color',
        ),
        migrations.AddField(
            model_name='marca',
            name='logo_horizontal_blanco',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='niska/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='logo_horizontal_color',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='niska/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='logo_horizontal_color_variante',
            field=models.ImageField(blank=True, help_text='imagenes 20*20', null=True, upload_to='niska/'),
        ),
    ]
