"""
Django settings for benitez project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path
#from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9*%w$ow!)u#3$rg+(w=o3sz6kf_p(e@dbted^*1l9lhecb$swi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Home',
    'Niska',
    'Girekstudio',
    'Vortice',
    'Zatuar',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'coupons.apps.CouponsConfig',
    'import_export',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'benitez.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',

            ],
        },
    },
]

WSGI_APPLICATION = 'benitez.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),


    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'


STATIC_ROOT=os.path.join(BASE_DIR, "static/")
'''STATICFILES_DIRS=[
   'static',
]'''

MEDIA_URL='/media/'
# MEDIA_ROOT='/var/www/benitez-master//media/'
MEDIA_ROOT=os.path.join(BASE_DIR,"media/")
#MEDIA_ROOT="/var/www/benitez-master/media/"

CART_SESSION_ID = 'cart'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'




# Crispy forms
#CRISPY_TEMPLATE_PACK = 'bootstrap4'
#CRISPY_ALLOWED_TEMPLATE_PACKS= "uni_form", "bootstrap3", "bootstrap4"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Stripe settings
STRIPE_PUBLISHABLE_KEY = 'pk_test_51QmeMJP7tA8xDTNIZUC0MUwqSJ8PCqSnbelrdXzjJ8Sz0HKYKCGJQvXL3YGmM1gqmT6FYj6TVEHcptth82Gbb6VV00NfEbjFi3' # Publishable key
STRIPE_SECRET_KEY = 'sk_test_51QmeMJP7tA8xDTNI2CQ4StWtsl8BXUAQ9hvp0UqW4ImL0kGQfKmce7nRAc8uPjBAfkPDygghZ1NyvoE0A1uHWza000LfejNdS9'      # Secret key
STRIPE_API_VERSION = '2022-08-01'
STRIPE_WEBHOOK_SECRET = ''

PAYPHONE_API_KEY = os.getenv("oVJ0zDE740mTPJrGMWcxNQ", "uDi3q4KHKdVhxrmkyZwUvwdMlDNs5K4SZUFjpbDUD-tOzx8jbYk8lIxTqtqr29f9tS13PkyNXnJE63WfiOAsVO1V7SK2ae2W4aM9bS-bfZBF1LcmKh7qXTRZYkbTWWK5vDn422_0O2RK22WEViHrFX7M8bfbP4gmVUm4uOYwzXqpYB0EMmIq6tnVHcWRsIwUuvgg_0TPwDVeiq_cfHJScMjj8fK4Z4LoJ6DCufrE3fvIpjfCipBnfFmSo5-3Ai_z5LwKQdFk8f_Nu9eUJ0BOQ0yd-uCorw6Qpt869YjH1GyiaKlKSxPyi0o48vZgG4fU8SlEELZLQLl3QLCnDhKZob7D2X8")
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")


# Redis settings
REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'vortice.ec@gmail.com'  # Tu correo electrónico
EMAIL_HOST_PASSWORD = 'wcdb ujft mlzc rssk'   # Tu contraseña de correo electrónico

# API DE WHATSAPP
#WHATSAPP_TOKEN = os.environ["WHATSAPP_TOKEN"]
#WHATSAPP_CALLBACK_TOKEN = os.environ["WHATSAPP_CALLBACK_TOKEN"]
#WHATSAPP_NUMBER_ID = os.environ["WHATSAPP_NUMBER_ID"]
#WHATSAPP_RECEIVER = os.environ["WHATSAPP_RECEIVER"]
