# Generated by Django 4.2.20 on 2026-05-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='EralySoft', max_length=100)),
                ('logo_principal', models.ImageField(help_text='Logo blanco para fondo oscuro', upload_to='eraly/')),
                ('logo_alternativo', models.ImageField(help_text='Logo oscuro para fondo claro', upload_to='eraly/')),
                ('favicon', models.ImageField(upload_to='eraly/')),
                ('email', models.EmailField(default='info@eralysoft.com', max_length=254)),
                ('email_soporte', models.EmailField(default='soporte@eralysoft.com', max_length=254)),
                ('telefono', models.CharField(default='099 999 9999', max_length=20)),
                ('telefono_2', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(default='593999999999', max_length=20)),
                ('direccion', models.TextField(default='Quito - Ecuador')),
                ('horario', models.CharField(default='Lun-Vie 9am-6pm, Sáb 9am-1pm', max_length=200)),
                ('meta_titulo', models.CharField(default='EralySoft - Soluciones Tecnológicas para tu Negocio', max_length=200)),
                ('meta_descripcion', models.TextField(default='Sistemas POS, páginas web, hosting, dominios, correos corporativos y facturación electrónica SRI')),
                ('meta_keywords', models.CharField(default='POS, facturación electrónica, páginas web, hosting, Ecuador', max_length=500)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Configuración de la empresa',
                'verbose_name_plural': 'Configuración de la empresa',
            },
        ),
    ]
