# Generated by Django 4.2.20 on 2026-05-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('titulo_seo', models.CharField(max_length=180)),
                ('titulo_hero', models.CharField(max_length=120)),
                ('subtitulo_hero', models.CharField(max_length=180)),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='landing/hero/')),
                ('titulo_beneficios', models.CharField(default='¿Por qué elegirnos?', max_length=120)),
                ('subtitulo_beneficios', models.CharField(blank=True, max_length=180)),
                ('categoria_titulo', models.CharField(max_length=160)),
                ('categoria_icono', models.CharField(default='fa-solid fa-utensils', max_length=80)),
                ('titulo_seccion', models.CharField(max_length=160)),
                ('descripcion_seccion', models.TextField(blank=True)),
                ('cta_titulo', models.CharField(max_length=160)),
                ('cta_texto', models.TextField(blank=True)),
                ('cta_boton_texto', models.CharField(default='Solicitar demo', max_length=80)),
                ('cta_boton_url', models.CharField(default='/contacto/', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TabLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('badge', models.CharField(max_length=100)),
                ('encabezado', models.CharField(max_length=160)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='fa-solid fa-circle', max_length=80)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='landing/tabs/')),
                ('boton_texto', models.CharField(default='Solicitar demo', max_length=80)),
                ('boton_url', models.CharField(default='/contacto/', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='Eraly.landingpage')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=180)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('moneda', models.CharField(default='$', max_length=10)),
                ('periodo', models.CharField(default='/mes', max_length=30)),
                ('destacado', models.BooleanField(default=False)),
                ('etiqueta', models.CharField(blank=True, max_length=80)),
                ('boton_texto', models.CharField(default='Contratar', max_length=80)),
                ('boton_url', models.CharField(default='/contacto/', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='Eraly.landingpage')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=160)),
                ('incluido', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='Eraly.planlanding')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='BeneficioLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=180)),
                ('icono', models.CharField(default='fa-solid fa-check', max_length=80)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='landing/beneficios/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('landing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='Eraly.landingpage')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
