# Generated by Django 4.2.20 on 2026-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0002_landingpage_tablanding_planlanding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiolanding',
            name='descripcion_1',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='beneficiolanding',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='landing/beneficios/'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='subtitulo2_beneficios',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
