# Generated by Django 4.2.20 on 2026-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0003_beneficiolanding_descripcion_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiolanding',
            name='descripcion_1',
            field=models.TextField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='beneficiolanding',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='eraly/'),
        ),
        migrations.AlterField(
            model_name='beneficiolanding',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='eraly/'),
        ),
    ]
