# Generated by Django 4.2.20 on 2026-05-23 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0004_alter_beneficiolanding_descripcion_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabLanding',
        ),
    ]
