# Generated by Django 4.2.20 on 2026-05-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0006_eralynewsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='imagen_hero',
            field=models.ImageField(blank=True, null=True, upload_to='eraly/'),
        ),
    ]
