# Generated by Django 4.2.20 on 2026-05-28 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0007_alter_landingpage_imagen_hero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlanding',
            name='moneda',
        ),
    ]
