# Generated by Django 4.2.20 on 2026-05-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0008_remove_planlanding_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('hosting', 'Hosting + Dominio'), ('web', 'Páginas Web'), ('correos', 'Correos Corporativos'), ('facturacion', 'Facturación SRI'), ('apps', 'Apps a Medida')], max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen_banner', models.ImageField(blank=True, null=True, upload_to='eraly/productos/')),
                ('imagen_cuadrada_1', models.ImageField(blank=True, null=True, upload_to='eraly/productos/')),
                ('imagen_cuadrada_2', models.ImageField(blank=True, null=True, upload_to='eraly/productos/')),
                ('boton_texto', models.CharField(default='Cotizar ahora', max_length=80)),
                ('boton_url', models.CharField(default='/eraly/contacto/', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Servicio Web',
                'verbose_name_plural': 'Servicios Web',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='beneficiolanding',
            options={'ordering': ['orden'], 'verbose_name': 'Beneficios  Sistemas POS', 'verbose_name_plural': 'Beneficios  Sistemas POS'},
        ),
        migrations.AlterModelOptions(
            name='caracteristicaplan',
            options={'ordering': ['orden'], 'verbose_name': 'Caracteristicas Plan  Sistemas POS', 'verbose_name_plural': 'Caracteristicas Plan  Sistemas POS'},
        ),
        migrations.AlterModelOptions(
            name='configuracionempresa',
            options={'verbose_name': 'Configuración Empresa POS', 'verbose_name_plural': 'Configuración Empresa POS'},
        ),
        migrations.AlterModelOptions(
            name='eralynewsletter',
            options={'ordering': ['-fecha'], 'verbose_name': 'Suscriptores Sistema POS', 'verbose_name_plural': 'Suscriptores Sistema POS'},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': ' Sistemas POS', 'verbose_name_plural': ' Sistemas POS'},
        ),
        migrations.AlterModelOptions(
            name='planlanding',
            options={'ordering': ['orden'], 'verbose_name': 'Plan  Sistemas POS', 'verbose_name_plural': 'Plan  Sistemas POS'},
        ),
        migrations.CreateModel(
            name='ServicioProductoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('beneficio', 'Beneficio'), ('servicio', 'Servicio'), ('documento', 'Documento'), ('faq', 'Pregunta Frecuente'), ('proceso', 'Proceso'), ('dominio', 'Dominio')], default='beneficio', max_length=30)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fa-solid fa-check', max_length=80)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('periodo', models.CharField(blank=True, max_length=30)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eraly/productos/items/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Eraly.servicioproducto')),
            ],
            options={
                'verbose_name': 'Item Servicio Web',
                'verbose_name_plural': 'Items Servicios Web',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanServicioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.CharField(default='/mes', max_length=30)),
                ('destacado', models.BooleanField(default=False)),
                ('boton_texto', models.CharField(default='Contratar', max_length=80)),
                ('boton_url', models.CharField(default='/eraly/contacto/', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_servicio', to='Eraly.servicioproducto')),
            ],
            options={
                'verbose_name': 'Plan Servicio Web',
                'verbose_name_plural': 'Planes Servicios Web',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='CaracteristicaPlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=180)),
                ('incluido', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas_servicio', to='Eraly.planservicioproducto')),
            ],
            options={
                'verbose_name': 'Característica Plan Servicio',
                'verbose_name_plural': 'Características Plan Servicio',
                'ordering': ['orden'],
            },
        ),
    ]
