# Generated by Django 4.2.20 on 2026-05-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0009_servicioproducto_alter_beneficiolanding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(default='fa-solid fa-check', max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Beneficio Servicio',
                'verbose_name_plural': 'Beneficios Servicio',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DominioServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.CharField(default='/año', max_length=30)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dominio Servicio',
                'verbose_name_plural': 'Dominios Servicio',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PlanServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('periodo', models.CharField(default='/mes', max_length=30)),
                ('destacado', models.BooleanField(default=False)),
                ('boton_texto', models.CharField(default='Contratar', max_length=80)),
                ('boton_url', models.CharField(default='/eraly/contacto/', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plan Servicio',
                'verbose_name_plural': 'Planes Servicio',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pregunta Servicio',
                'verbose_name_plural': 'Preguntas Servicio',
                'ordering': ['orden'],
            },
        ),
        migrations.RemoveField(
            model_name='planservicioproducto',
            name='servicio',
        ),
        migrations.RenameField(
            model_name='servicioproducto',
            old_name='imagen_cuadrada_1',
            new_name='imagen_1',
        ),
        migrations.RenameField(
            model_name='servicioproducto',
            old_name='imagen_cuadrada_2',
            new_name='imagen_2',
        ),
        migrations.DeleteModel(
            name='ServicioProductoItem',
        ),
        migrations.AddField(
            model_name='preguntaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='Eraly.servicioproducto'),
        ),
        migrations.AddField(
            model_name='planservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='Eraly.servicioproducto'),
        ),
        migrations.AddField(
            model_name='dominioservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='Eraly.servicioproducto'),
        ),
        migrations.AddField(
            model_name='beneficioservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='Eraly.servicioproducto'),
        ),
        migrations.AlterField(
            model_name='caracteristicaplanservicio',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='Eraly.planservicio'),
        ),
        migrations.DeleteModel(
            name='PlanServicioProducto',
        ),
    ]
