# Generated by Django 4.2.20 on 2026-05-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0010_beneficioservicio_dominioservicio_planservicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficioservicio',
            options={'ordering': ['orden'], 'verbose_name': '02. Beneficio del Servicio', 'verbose_name_plural': '02. Beneficios del Servicio'},
        ),
        migrations.AlterModelOptions(
            name='caracteristicaplanservicio',
            options={'ordering': ['orden'], 'verbose_name': '05. Característica del Plan', 'verbose_name_plural': '05. Características del Plan'},
        ),
        migrations.AlterModelOptions(
            name='dominioservicio',
            options={'ordering': ['orden'], 'verbose_name': '03. Dominio del Servicio', 'verbose_name_plural': '03. Dominios del Servicio'},
        ),
        migrations.AlterModelOptions(
            name='planservicio',
            options={'ordering': ['orden'], 'verbose_name': '04. Plan del Servicio', 'verbose_name_plural': '04. Planes del Servicio'},
        ),
        migrations.AlterModelOptions(
            name='preguntaservicio',
            options={'ordering': ['orden'], 'verbose_name': '06. Pregunta Frecuente', 'verbose_name_plural': '06. Preguntas Frecuentes'},
        ),
        migrations.AlterModelOptions(
            name='servicioproducto',
            options={'ordering': ['orden'], 'verbose_name': '01. Servicio Web', 'verbose_name_plural': '01. Servicios Web'},
        ),
    ]
