# Generated by Django 4.2.20 on 2026-05-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0011_alter_beneficioservicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiolanding',
            options={'ordering': ['orden'], 'verbose_name': '11. Beneficio POS', 'verbose_name_plural': '11. Beneficios POS'},
        ),
        migrations.AlterModelOptions(
            name='caracteristicaplan',
            options={'ordering': ['orden'], 'verbose_name': '13. Característica Plan POS', 'verbose_name_plural': '13. Características Plan POS'},
        ),
        migrations.AlterModelOptions(
            name='configuracionempresa',
            options={'verbose_name': '00. Configuración Empresa', 'verbose_name_plural': '00. Configuración Empresa'},
        ),
        migrations.AlterModelOptions(
            name='eralynewsletter',
            options={'ordering': ['-fecha'], 'verbose_name': '20. Suscriptor', 'verbose_name_plural': '20. Suscriptores'},
        ),
        migrations.AlterModelOptions(
            name='landingpage',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': '10. Solución POS', 'verbose_name_plural': '10. Soluciones POS'},
        ),
        migrations.AlterModelOptions(
            name='planlanding',
            options={'ordering': ['orden'], 'verbose_name': '12. Plan POS', 'verbose_name_plural': '12. Planes POS'},
        ),
    ]
