# Generated by Django 4.2.20 on 2026-05-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0012_alter_beneficiolanding_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planservicio',
            name='color',
            field=models.CharField(default='#00839a', max_length=20),
        ),
        migrations.AddField(
            model_name='planservicio',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='planservicio',
            name='icono',
            field=models.CharField(default='fa-solid fa-check', max_length=80),
        ),
    ]
