# Generated by Django 4.2.20 on 2026-05-30 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0013_planservicio_color_planservicio_etiqueta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicioWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=250)),
                ('etiqueta', models.CharField(blank=True, default='', max_length=80)),
                ('icono', models.CharField(default='fa-solid fa-globe', max_length=80)),
                ('color', models.CharField(default='#00839a', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_web', to='Eraly.servicioproducto')),
            ],
            options={
                'verbose_name': '07. Tipo de Servicio Web',
                'verbose_name_plural': '07. Tipos de Servicio Web',
                'ordering': ['orden'],
            },
        ),
    ]
