# Generated by Django 4.2.20 on 2026-05-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0014_tiposervicioweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='planservicio',
            name='tipo_web',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='Eraly.tiposervicioweb'),
        ),
    ]
