# Generated by Django 4.2.20 on 2026-05-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0015_planservicio_tipo_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicioproducto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='eraly/productos/'),
        ),
        migrations.AddField(
            model_name='servicioproducto',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='eraly/productos/'),
        ),
    ]
