# Generated by Django 4.2.20 on 2026-05-31 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0016_servicioproducto_imagen_3_servicioproducto_imagen_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='ciudad',
            field=models.CharField(default='Machala', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_badge',
            field=models.CharField(default='Soporte 24/7', max_length=100),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_banner',
            field=models.ImageField(blank=True, null=True, upload_to='eraly/contacto/'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_subtitulo',
            field=models.CharField(default='Estamos aquí para ayudarte', max_length=180),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_texto_intro',
            field=models.TextField(default='Cuéntanos tu proyecto y te asesoramos sin compromiso.'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_texto_soporte',
            field=models.TextField(default='Nuestro equipo de soporte está disponible para atenderte.'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_titulo',
            field=models.CharField(default='Contáctanos', max_length=120),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_titulo_intro',
            field=models.CharField(default='Hablemos', max_length=160),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='contacto_titulo_soporte',
            field=models.CharField(default='¿Necesitas ayuda técnica?', max_length=160),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='mapa_iframe',
            field=models.TextField(blank=True, help_text='Pegar iframe de Google Maps'),
        ),
        migrations.AddField(
            model_name='configuracionempresa',
            name='oficina',
            field=models.CharField(default='Oficina principal', max_length=150),
        ),
    ]
