# Generated by Django 4.2.20 on 2026-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eraly', '0017_configuracionempresa_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionempresa',
            name='imagen_compartir',
            field=models.ImageField(blank=True, help_text='Imagen para WhatsApp, Facebook y LinkedIn (1200x630)', null=True, upload_to='eraly/'),
        ),
    ]
