# Generated by Django 4.1.13 on 2025-02-04 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_coupon_created_ad_coupon_used_alter_coupon_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='created_ad',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='used',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(help_text='Percentage vaule (0 to 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
