# Generated by Django 4.0.6 on 2024-10-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('activo', models.BooleanField(default=False)),
                ('link_exterior', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_marcas', models.CharField(blank=True, max_length=100, null=True)),
                ('slider', models.ImageField(blank=True, null=True, upload_to='slider_marcas')),
            ],
            options={
                'verbose_name_plural': '2. Empresas',
            },
        ),
        migrations.CreateModel(
            name='Marca_benitez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='empresas/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresas')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('mision', models.TextField(blank=True, max_length=400, null=True)),
                ('vision', models.TextField(blank=True, max_length=400, null=True)),
                ('nosotros', models.TextField(blank=True, max_length=800, null=True)),
                ('frase', models.TextField(blank=True, max_length=200, null=True)),
                ('autor', models.CharField(blank=True, max_length=15, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('horariosb', models.CharField(blank=True, default=1, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Grupo Benitez ',
            },
        ),
    ]
