# Generated by Django 4.1.13 on 2025-01-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_product_image_1_product_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slider',
            field=models.BooleanField(default=False),
        ),
    ]
