# Generated by Django 4.1.13 on 2025-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_image_1_alter_product_image_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icono',
            field=models.ImageField(blank=True, upload_to='colexin'),
        ),
    ]
