# Generated by Django 4.2.30 on 2026-09-13 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogColexin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen_principal', models.ImageField(help_text='Imagen vertical recomendada: 800 x 1145 px', upload_to='colexin/blog/principal/')),
                ('imagen_horizontal', models.ImageField(blank=True, help_text='Imagen horizontal recomendada: 1920 x 1080 px', null=True, upload_to='colexin/blog/horizontal/')),
                ('contenido', models.TextField(help_text='Puede escribir directamente código HTML.')),
                ('video_youtube', models.URLField(blank=True, help_text='Pegue el enlace completo de YouTube. Ejemplo: https://youtu.be/xxxxxxxxxxx', max_length=500)),
                ('activo', models.BooleanField(default=True, help_text='Visible en el sitio web')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar como publicación destacada')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BLOG COLEXIN- 02 Publicación',
                'verbose_name_plural': 'BLOG COLEXIN- 02 Publicaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaBlogColexin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BLOG COLEXIN- 01 Categoría',
                'verbose_name_plural': 'BLOG COLEXIN- 01 Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenBlogColexin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='colexin/blog/galeria/')),
                ('titulo', models.CharField(blank=True, help_text='Descripción opcional de la imagen', max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='shop.blogcolexin')),
            ],
            options={
                'verbose_name': 'BLOG COLEXIN- 03 Imagen',
                'verbose_name_plural': 'BLOG COLEXIN- 03 Galería',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='blogcolexin',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones_colexin', to='shop.categoriablogcolexin'),
        ),
    ]
