# Generated by Django 4.2.30 on 2026-09-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_blogcolexin_categoriablogcolexin_imagenblogcolexin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='meta_about',
            field=models.ImageField(blank=True, help_text='Imagen para compartir la página Nosotros. Recomendado: 1200 × 630 px', null=True, upload_to='colexin/meta/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='meta_contacto',
            field=models.ImageField(blank=True, help_text='Imagen para compartir la página de contacto. Recomendado: 1200 × 630 px', null=True, upload_to='colexin/meta/'),
        ),
        migrations.AddField(
            model_name='marca',
            name='meta_inicio',
            field=models.ImageField(blank=True, help_text='Imagen para compartir la página de inicio. Recomendado: 1200 × 630 px', null=True, upload_to='colexin/meta/'),
        ),
    ]
