# Generated by Django 4.2.30 on 2026-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_marca_meta_about_marca_meta_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='meta_blog',
            field=models.ImageField(blank=True, help_text='Imagen para compartir el blog. Recomendado: 1200 × 630 px', null=True, upload_to='colexin/meta/'),
        ),
    ]
