# Generated by Django 4.0.6 on 2024-10-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficio', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': '5. Zatuar Beneficios',
            },
        ),
        migrations.CreateModel(
            name='Clasif_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_producto', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': '9.4. Clasificaciòn de Producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_export', models.CharField(blank=True, max_length=100, null=True)),
                ('client_logo', models.FileField(blank=True, help_text='200x200', null=True, upload_to='zatuar/')),
                ('detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('foto', models.FileField(blank=True, help_text='1280x500', null=True, upload_to='zatuar/')),
                ('pagweb', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '01.0 Clientes',
            },
        ),
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_color', models.CharField(blank=True, max_length=30, null=True)),
                ('codigo_color', models.CharField(blank=True, max_length=8, null=True)),
            ],
            options={
                'verbose_name_plural': '9.5. Color',
            },
        ),
        migrations.CreateModel(
            name='Contacto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('horario', models.CharField(blank=True, default=1, max_length=100, null=True)),
                ('horariosb', models.CharField(blank=True, default=1, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '3. Contacto Empresa',
            },
        ),
        migrations.CreateModel(
            name='Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('principal', models.BooleanField(default=False)),
                ('img', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='zatuar/')),
            ],
            options={
                'verbose_name_plural': '9.2. Descarga',
            },
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('image2', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('image3', models.FileField(blank=True, null=True, upload_to='zatuar/')),
            ],
            options={
                'verbose_name_plural': '9.1. Detalles',
            },
        ),
        migrations.CreateModel(
            name='Ficha_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=50, null=True)),
                ('ficha', models.FileField(blank=True, help_text='pdf', null=True, upload_to='zatuar/')),
            ],
            options={
                'verbose_name_plural': '9.5. Producto Ficha Tecnica',
            },
        ),
        migrations.CreateModel(
            name='Galeria_Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '9. Galeria_Proceso',
            },
        ),
        migrations.CreateModel(
            name='Identidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '7. Zatuar es',
            },
        ),
        migrations.CreateModel(
            name='Linea_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('linea', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.FileField(blank=True, help_text='100x100', null=True, upload_to='products/')),
            ],
            options={
                'verbose_name_plural': '9.3 Linea de Producto',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '9.5. Materiales',
            },
        ),
        migrations.CreateModel(
            name='Personalizaion_Poducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='zatuar/')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '6. Perzonalizacion de Productos',
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, max_length=200, null=True)),
                ('img1', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('ti1', models.CharField(blank=True, max_length=30, null=True)),
                ('img2', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('ti2', models.CharField(blank=True, max_length=30, null=True)),
                ('img3', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('ti3', models.CharField(blank=True, max_length=30, null=True)),
                ('ti4', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '8. Proceso',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image_a', models.FileField(blank=True, help_text='100x100', null=True, upload_to='zatuar/')),
                ('image_b', models.FileField(blank=True, help_text='100x100', null=True, upload_to='zatuar/')),
                ('foto_slider', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('tamanio', models.CharField(blank=True, max_length=30, null=True)),
                ('gramaje', models.CharField(blank=True, max_length=30, null=True)),
                ('nuevo', models.BooleanField(default=False)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('disponibilidad', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('clasif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zatuar.clasif_producto')),
                ('ficha_tecnica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.ficha_product')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.materiales')),
            ],
            options={
                'verbose_name_plural': '9.5. Producto',
            },
        ),
        migrations.CreateModel(
            name='Redes_sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Redes Sociales',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('slider', models.FileField(blank=True, help_text='1884x529', null=True, upload_to='zatuar/')),
            ],
            options={
                'verbose_name_plural': '1. Slider',
            },
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '9.5. Tallas',
            },
        ),
        migrations.CreateModel(
            name='Texturs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textura', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': '9.5. Texturas',
            },
        ),
        migrations.CreateModel(
            name='Zatuar_marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('logo_blanco', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('logo_negro', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='zatuar/')),
                ('imagen', models.FileField(blank=True, help_text='400x400', null=True, upload_to='zatuar/')),
                ('imagen_2', models.FileField(blank=True, help_text='400x400', null=True, upload_to='zatuar/')),
                ('portada', models.FileField(blank=True, help_text='1280x400', null=True, upload_to='zatuar/')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '2. Zatuar Marca',
            },
        ),
        migrations.CreateModel(
            name='Tallas_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
                ('talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.tallas')),
            ],
            options={
                'verbose_name_plural': '9.5. Talla Producto',
            },
        ),
        migrations.CreateModel(
            name='Producto_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('slider', models.FileField(blank=True, help_text='1884x529', null=True, upload_to='zatuar/')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '9.8. Slider',
            },
        ),
        migrations.CreateModel(
            name='Producto_Personalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='zatuar/')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '9.7. Producto Personalizacion',
            },
        ),
        migrations.CreateModel(
            name='Producto_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('galeria_articulo', models.FileField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='zatuar/')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '9.6. Producto Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Producto_cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_producto', models.FileField(blank=True, help_text='500x500', null=True, upload_to='zatuar/')),
                ('portada', models.FileField(blank=True, help_text='600x400', null=True, upload_to='zatuar/')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.cliente')),
            ],
            options={
                'verbose_name_plural': '9.9.1 Mandil Cliente',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='textura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.texturs'),
        ),
        migrations.CreateModel(
            name='Galeria_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.FileField(blank=True, help_text='500x500', null=True, upload_to='zatuar/')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.cliente')),
            ],
            options={
                'verbose_name_plural': '01.1 Clientes-Galeria',
            },
        ),
        migrations.CreateModel(
            name='Color_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.colores')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.product')),
            ],
            options={
                'verbose_name_plural': '9.5. Color Producto',
            },
        ),
        migrations.AddField(
            model_name='clasif_producto',
            name='linea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Zatuar.linea_product'),
        ),
    ]
