# Generated by Django 4.0.6 on 2024-10-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto_cliente',
            name='client',
        ),
        migrations.RemoveField(
            model_name='producto_slider',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto_imagen',
            name='orden',
        ),
        migrations.DeleteModel(
            name='Galeria_Cliente',
        ),
        migrations.DeleteModel(
            name='Producto_cliente',
        ),
        migrations.DeleteModel(
            name='Producto_Slider',
        ),
    ]
