# Generated by Django 4.0.6 on 2024-10-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0002_remove_producto_cliente_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='detalle',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='pagweb',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='linea_product',
            name='imagen',
            field=models.FileField(blank=True, help_text='100x100', null=True, upload_to='zatuar/'),
        ),
    ]
