# Generated by Django 4.0.6 on 2024-10-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0003_remove_cliente_detalle_remove_cliente_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto_empresa',
            name='horarioc',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='horariosd',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
