# Generated by Django 4.0.6 on 2024-10-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zatuar', '0004_contacto_empresa_horarioc_contacto_empresa_horariosd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto_empresa',
            old_name='horario',
            new_name='horario1',
        ),
        migrations.RenameField(
            model_name='contacto_empresa',
            old_name='horarioc',
            new_name='horario2',
        ),
        migrations.RenameField(
            model_name='contacto_empresa',
            old_name='horariosb',
            new_name='horario3',
        ),
        migrations.RenameField(
            model_name='contacto_empresa',
            old_name='horariosd',
            new_name='horario4',
        ),
    ]
