# Generated by Django 4.1.13 on 2025-02-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=450, null=True),
        ),
    ]
