# Generated by Django 4.0.6 on 2024-10-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'PROD- 01. Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Clasif_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_producto', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': 'PROD- 03. Clasificación de Producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('sitio', models.CharField(blank=True, max_length=90, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='girekstudio')),
            ],
            options={
                'verbose_name_plural': 'PROY- 01 Clientes ',
            },
        ),
        migrations.CreateModel(
            name='Editables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_1_imagen_01', models.FileField(blank=True, help_text='Encabezado slider  1149x800', null=True, upload_to='girekstudio/')),
                ('sec_1_imagen_02', models.FileField(blank=True, help_text='Encabezado slider 1149x800', null=True, upload_to='girekstudio/')),
                ('sec_1_imagen_03', models.FileField(blank=True, help_text='Encabezado slider 1149x800', null=True, upload_to='girekstudio/')),
                ('sec_1_subsubti_01', models.CharField(blank=True, help_text='Encabezado Texto Vertical', max_length=200, null=True)),
                ('sec_1_titulo_01', models.CharField(blank=True, help_text='Encabezado  Titulo', max_length=200, null=True)),
                ('sec_1_subti_01', models.CharField(blank=True, help_text='Encabezado  subtitulo', max_length=200, null=True)),
                ('sec_1_imagen_1', models.FileField(blank=True, help_text='Bajo de encabezado  imagen 421x524', null=True, upload_to='girekstudio/')),
                ('sec_1_imagen_2', models.FileField(blank=True, help_text='Bajo de encabezado  imagen 500x614', null=True, upload_to='girekstudio/')),
                ('sec_1_imagen_3', models.FileField(blank=True, help_text='Bajo de encabezado  imagen 261x313', null=True, upload_to='girekstudio/')),
                ('sec_1_subti_1', models.CharField(blank=True, help_text='Bajo de encabezado', max_length=200, null=True)),
                ('sec_1_titulo_1', models.CharField(blank=True, help_text='Bajo de encabezado', max_length=200, null=True)),
                ('sec_1_detalle_1', models.TextField(blank=True, help_text='Bajo de encabezado', max_length=500, null=True)),
                ('frase', models.CharField(blank=True, help_text='Frase movimiento', max_length=800, null=True)),
                ('sec_1_titulo_2', models.CharField(blank=True, help_text='Bajo de servicio', max_length=200, null=True)),
                ('sec_1_subti_2', models.CharField(blank=True, help_text='Bajo de servicio', max_length=200, null=True)),
                ('sec_1_titulo_3', models.CharField(blank=True, help_text='Opcion Titulo 1', max_length=200, null=True)),
                ('sec_1_subti_3', models.CharField(blank=True, help_text='Opcion detalle 1', max_length=200, null=True)),
                ('sec_1_titulo_4', models.CharField(blank=True, help_text='Opcion Titulo 2', max_length=200, null=True)),
                ('sec_1_subti_4', models.CharField(blank=True, help_text='Opcion detalle 2', max_length=200, null=True)),
                ('sec_1_titulo_5', models.CharField(blank=True, help_text='Opcion Titulo 3', max_length=200, null=True)),
                ('sec_1_subti_5', models.CharField(blank=True, help_text='Opcion detalle 3', max_length=200, null=True)),
                ('sec_1_titulo_6', models.CharField(blank=True, help_text='Bajo parte izq. de equipo', max_length=200, null=True)),
                ('sec_1_titulo_7', models.CharField(blank=True, help_text='Pie de pag izq. frase', max_length=200, null=True)),
                ('sec_1_imagen_4', models.FileField(blank=True, help_text='imagen pie de pag 1126x630', null=True, upload_to='girekstudio/')),
                ('sec_2_subti_1', models.CharField(blank=True, help_text='Agencia encabezado text verti', max_length=200, null=True)),
                ('sec_2_titulo_1', models.CharField(blank=True, help_text='Agencia encabezado text horiz', max_length=200, null=True)),
                ('sec_2_imagen_1', models.FileField(blank=True, help_text='Agencia encabezado imagen 1149x800', null=True, upload_to='girekstudio/')),
                ('sec_2_imagen_rota', models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/')),
                ('sec_2_imag_rota_ico', models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/')),
                ('sec_2_titulo_2', models.CharField(blank=True, help_text='Agencia bajo de encabezado', max_length=200, null=True)),
                ('sec_2_palabra', models.CharField(blank=True, help_text='Agencia bajo de encabezado palabra ', max_length=200, null=True)),
                ('sec_2_detalle_2', models.TextField(blank=True, help_text='Agencia a lado de imagen rotando y frase ', max_length=500, null=True)),
                ('sec_2_clientes', models.CharField(blank=True, help_text='Numero de Clientes', max_length=200, null=True)),
                ('sec_2_clientes_detalle', models.CharField(blank=True, help_text='Detalle Clientes', max_length=200, null=True)),
                ('sec_2_proyectos', models.CharField(blank=True, help_text='Numero proyectos', max_length=200, null=True)),
                ('sec_2_proyectos_detalle', models.CharField(blank=True, help_text='Detalle proyectos', max_length=200, null=True)),
                ('sec_2_anios_exper', models.CharField(blank=True, help_text='Anios de experiencia', max_length=200, null=True)),
                ('sec_2_anios_exper_detalle', models.CharField(blank=True, help_text='Detalle Crecimiento', max_length=200, null=True)),
                ('sec_2_crecimi', models.CharField(blank=True, help_text='Numero porcentaje crecimiento', max_length=200, null=True)),
                ('sec_2_crecimi_detalle', models.CharField(blank=True, help_text='Detalle crecimiento', max_length=200, null=True)),
                ('sec_2_imagen_3', models.FileField(blank=True, help_text='Bajo de encabezado  imagen 421x524', null=True, upload_to='girekstudio/')),
                ('sec_2_imagen_4', models.FileField(blank=True, help_text='Bajo de encabezado  imagen 500x614', null=True, upload_to='girekstudio/')),
                ('sec_2_imagen_5', models.FileField(blank=True, help_text='Bajo de encabezado  imagen 261x313', null=True, upload_to='girekstudio/')),
                ('sec_2_subti_4', models.CharField(blank=True, help_text='Subtitulo pequeño lado derecho', max_length=200, null=True)),
                ('sec_2_titulo_4', models.CharField(blank=True, help_text='Titulo grande lado derecho', max_length=200, null=True)),
                ('sec_2_detalle_4', models.TextField(blank=True, help_text='Detalle lado derecho', max_length=500, null=True)),
                ('sec_3_subti_1', models.CharField(blank=True, help_text='Servicios encabezado text verti', max_length=200, null=True)),
                ('sec_3_titulo_1', models.CharField(blank=True, help_text='Servicios encabezado text horiz', max_length=200, null=True)),
                ('sec_3_imagen_1', models.FileField(blank=True, help_text='Servicios encabezado imagen 1149x800', null=True, upload_to='girekstudio/')),
                ('sec_3_titulo_2', models.CharField(blank=True, help_text='Servicios bajo de encabezado', max_length=200, null=True)),
                ('sec_3_subti_2', models.CharField(blank=True, help_text='Servicios bajo de encabezado', max_length=200, null=True)),
                ('sec_3_imagen', models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/')),
                ('sec_4_titulo_1', models.CharField(blank=True, help_text='Portafolio encabezado', max_length=200, null=True)),
                ('sec_4_detalle', models.TextField(blank=True, help_text='Portafolio Detalle encabezado', max_length=500, null=True)),
                ('sec_4_imagen', models.FileField(blank=True, help_text='Portafolio texto rotativo', null=True, upload_to='girekstudio/')),
                ('sec_4_imag_rota_ico', models.FileField(blank=True, help_text='Portafolio icono ', null=True, upload_to='girekstudio/')),
                ('sec_5_subti_1', models.CharField(blank=True, help_text='Contacto encabezado text verti', max_length=200, null=True)),
                ('sec_5_titulo_1', models.CharField(blank=True, help_text='Contacto encabezado text horiz', max_length=200, null=True)),
                ('sec_5_imagen_1', models.FileField(blank=True, help_text='Contacto encabezado imagen 1149x800', null=True, upload_to='girekstudio/')),
                ('sec_5_imagen_2', models.FileField(blank=True, help_text='Contacto encabezado imagen 1149x800', null=True, upload_to='girekstudio/')),
                ('estudio', models.TextField(blank=True, max_length=800, null=True)),
                ('mision', models.TextField(blank=True, max_length=400, null=True)),
                ('vision', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'GI- 02 Editable pag Webs',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(blank=True, null=True, upload_to='girekstudio')),
                ('foto_2', models.FileField(blank=True, null=True, upload_to='girekstudio')),
                ('nombre', models.CharField(blank=True, max_length=90, null=True)),
                ('cargo', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': 'TEAM- 01 Equipo de trabajo ',
            },
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField(blank=True, null=True)),
                ('autor', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': 'GI- 03 Frases',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('logo_blanco', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('logo_gris', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('logo_negro', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
            ],
            options={
                'verbose_name_plural': 'GI- 01 Marca',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portafolio', models.CharField(blank=True, max_length=90, null=True)),
                ('visualizaciones', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'PROY- 02 Tema Protafolio',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.CharField(choices=[('stock', 'stock'), ('no_stock', 'no_stock')], default='stock', max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('caracteristicas', models.TextField(blank=True, max_length=500, null=True)),
                ('tamanos', models.TextField(blank=True, max_length=500, null=True)),
                ('material', models.TextField(blank=True, max_length=500, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clasif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.clasif_producto')),
            ],
            options={
                'verbose_name_plural': 'PROD- 04. Producto',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('icono', models.CharField(blank=True, max_length=20, null=True)),
                ('inicio', models.BooleanField(default=False, help_text='Para Ver en Inicio')),
                ('img_direc', models.BooleanField(default=False, help_text='Sec Agencia img activar si numero orden es  impar ')),
                ('white', models.BooleanField(default=False, help_text='Activar en numeros impar - tono claro en fondo')),
                ('line', models.BooleanField(default=False, help_text='Activar en numeros par - tono gris en fondo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='girekstudio/')),
                ('imagen_rota', models.FileField(blank=True, help_text='servicios texto rotativo', null=True, upload_to='girekstudio/')),
                ('imag_rota_ico', models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('palabra', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField(blank=True, default='', null=True)),
                ('imag_serv_princi', models.ImageField(blank=True, help_text='Imagen principal Inicio', null=True, upload_to='girekstudio/')),
                ('imag_serv_1', models.ImageField(blank=True, help_text='Imagen horizontal', null=True, upload_to='girekstudio/')),
                ('imag_serv_2', models.ImageField(blank=True, help_text='Imagen cuadrada', null=True, upload_to='girekstudio/')),
                ('video_link', models.CharField(blank=True, help_text='Pegar link video de youtube', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'SERV- 01 Servicios',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(blank=True, null=True, upload_to='girekstudio/')),
                ('titulo', models.CharField(blank=True, max_length=90, null=True)),
                ('sub_titulo', models.TextField(blank=True, max_length=500, null=True)),
                ('frase', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=90, null=True)),
                ('direccion', models.CharField(blank=True, max_length=90, null=True)),
                ('celular', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'verbose_name_plural': 'TEAM- 02 Sucursales ',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('img_izq', models.BooleanField(default=False, help_text='imagen a la izquierda ')),
                ('img_dere', models.BooleanField(default=False, help_text='imagen a la izquierda ')),
                ('img_central', models.BooleanField(default=False, help_text='imagen a la izquierda ')),
                ('fecha', models.DateField()),
                ('nombreproyecto', models.CharField(blank=True, help_text='Texto de maximo 120 caracteres', max_length=120, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video_vertical', 'video_vertical'), ('video', 'video')], default='imagen', max_length=20)),
                ('imagen', models.FileField(blank=True, help_text='imagen proyecto 851x315', null=True, upload_to='girekstudio/')),
                ('imagen_rectang', models.FileField(blank=True, help_text='imagen proyecto rectangular 851x315', null=True, upload_to='girekstudio/')),
                ('link', models.CharField(blank=True, max_length=250, null=True)),
                ('detalle_2', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.cliente')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.portafolio')),
            ],
            options={
                'verbose_name_plural': 'PROY- 03 Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(blank=True, null=True, upload_to='girekstudio/')),
                ('detalle', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.ciudad')),
            ],
            options={
                'verbose_name_plural': 'PROD- 02. Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto_Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria_articulo', models.ImageField(blank=True, help_text='imagen producto 800x800', null=True, upload_to='girekstudio')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.producto')),
            ],
            options={
                'verbose_name_plural': 'PROD- 05. Producto Imagenes',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.proveedor'),
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_activo', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.servicio')),
            ],
            options={
                'verbose_name_plural': 'SERV- 03 Planes',
            },
        ),
        migrations.CreateModel(
            name='Plan_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('info_1', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.planes')),
            ],
            options={
                'verbose_name_plural': 'SERV- 03.5 Plan Lista ',
            },
        ),
        migrations.CreateModel(
            name='Lista_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primera_colu', models.BooleanField(default=False, help_text='Activar para enviar a primera columna')),
                ('Segunda_colu', models.BooleanField(default=False, help_text='Activar para enviar a segunda columna')),
                ('lista_serv', models.CharField(blank=True, max_length=200, null=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.servicio')),
            ],
            options={
                'verbose_name_plural': 'SERV- 01.1 Servicios Lista',
            },
        ),
        migrations.CreateModel(
            name='Imagenesproyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_cuadra', models.BooleanField(default=False)),
                ('imagen_rectangu', models.BooleanField(default=False)),
                ('galeriaproyecto', models.FileField(upload_to='girekstudio/')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.proyecto')),
            ],
            options={
                'verbose_name_plural': 'PROY- 04 Proyecto Imagenes',
            },
        ),
        migrations.CreateModel(
            name='Imag_Video_Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='girekstudio/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.servicio')),
            ],
            options={
                'verbose_name_plural': 'SERV- 02 Imagenes / Video Servicios ',
            },
        ),
        migrations.CreateModel(
            name='Contacto_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('tiktok', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=15, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=11, null=True)),
                ('celular2', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('calle', models.CharField(blank=True, max_length=100, null=True)),
                ('mapa', models.TextField(blank=True, max_length=500, null=True)),
                ('representante', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Girekstudio.ciudad')),
            ],
            options={
                'verbose_name_plural': 'GI- 04 Contácto',
            },
        ),
    ]
