# Generated by Django 4.0.6 on 2024-10-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0002_rename_sec_3_imagen_editables_sec_3_imag_rota_ico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editables',
            name='sec_3_imagen_rota',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
    ]
