# Generated by Django 4.0.6 on 2024-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0003_editables_sec_3_imagen_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='editables',
            name='sec_4_imagen_rota',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_4_imag_rota_ico',
            field=models.FileField(blank=True, help_text='Agencia texto rotativo', null=True, upload_to='girekstudio/'),
        ),
        migrations.AlterField(
            model_name='editables',
            name='sec_4_imagen',
            field=models.FileField(blank=True, help_text='Portafolio imagen encabezado', null=True, upload_to='girekstudio/'),
        ),
    ]
