# Generated by Django 4.0.6 on 2024-10-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0004_editables_sec_4_imagen_rota_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imag_serv_princi',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
    ]
