# Generated by Django 4.0.6 on 2025-01-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0007_proyecto_tipo_video_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='linkweb',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
