# Generated by Django 4.0.6 on 2025-01-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0008_proyecto_linkweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='principal',
            field=models.BooleanField(default=False, help_text='Activar para que salga en la pagina principal'),
        ),
    ]
