# Generated by Django 4.0.6 on 2025-01-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0010_remove_imag_video_servicio_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imag_video_servicio',
            name='archivo',
        ),
        migrations.AddField(
            model_name='imag_video_servicio',
            name='activar_imagen',
            field=models.BooleanField(default=False, help_text='Activar si es imagen'),
        ),
        migrations.AddField(
            model_name='imag_video_servicio',
            name='activar_video',
            field=models.BooleanField(default=False, help_text='Activar si es video'),
        ),
        migrations.AddField(
            model_name='imag_video_servicio',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de Servicio', null=True, upload_to='girekstudio/'),
        ),
    ]
