# Generated by Django 4.0.6 on 2025-01-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0011_remove_imag_video_servicio_archivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imag_video_servicio',
            name='activar_imagen',
        ),
        migrations.RemoveField(
            model_name='imag_video_servicio',
            name='activar_video',
        ),
        migrations.RemoveField(
            model_name='imag_video_servicio',
            name='link_video',
        ),
        migrations.RemoveField(
            model_name='imag_video_servicio',
            name='tipo_archivo',
        ),
    ]
