# Generated by Django 4.2.20 on 2025-06-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0013_alter_producto_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=False, help_text='Activo para ser visualizado'),
        ),
    ]
