# Generated by Django 4.2.20 on 2025-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0014_servicio_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='principal',
            field=models.BooleanField(default=False, help_text='Pincipal para ser visualizado en el inicio'),
        ),
    ]
