# Generated by Django 4.2.20 on 2025-12-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0015_servicio_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=False, help_text='Activo para ser visualizado'),
        ),
    ]
