# Generated by Django 4.2.20 on 2025-12-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0016_producto_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='Activo para ser visualizado'),
        ),
    ]
