# Generated by Django 4.2.30 on 2026-09-13 12:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0017_alter_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen_principal', models.ImageField(help_text='Imagen recomendada: 1200 x 700 px', upload_to='girekstudio/blog/principal/')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('video_youtube', models.URLField(blank=True, help_text='Pegue el enlace completo de YouTube. Ejemplo: https://youtu.be/xxxxxxxxxxx', max_length=500)),
                ('activo', models.BooleanField(default=True, help_text='Visible en el sitio web')),
                ('destacado', models.BooleanField(default=False, help_text='Mostrar como publicación destacada')),
                ('fecha_publicacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BLOG- 02 Publicación',
                'verbose_name_plural': 'BLOG- 02 Publicaciones',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'BLOG- 01 Categoría',
                'verbose_name_plural': 'BLOG- 01 Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ImagenBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='girekstudio/blog/galeria/')),
                ('titulo', models.CharField(blank=True, help_text='Texto opcional de la imagen', max_length=150)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='Girekstudio.blog')),
            ],
            options={
                'verbose_name': 'BLOG- 03 Imagen de galería',
                'verbose_name_plural': 'BLOG- 03 Galería de imágenes',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publicaciones', to='Girekstudio.categoriablog'),
        ),
    ]
