# Generated by Django 4.2.30 on 2026-09-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0018_blog_categoriablog_imagenblog_blog_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='contenido',
            field=models.TextField(),
        ),
    ]
