# Generated by Django 4.2.30 on 2026-09-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Girekstudio', '0019_alter_blog_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen_horizontal',
            field=models.FileField(blank=True, null=True, upload_to='girekstudio/blog/'),
        ),
    ]
